spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:h2:mem:inventory;DB_CLOSE_ON_EXIT=FALSE
    username: inventory_user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true

  graphql:
    graphiql:
      enabled: true

server:
  port: 5000
  http2:
    enabled: true