INSERT INTO item_category (id, name) VALUES (1, 'MEDICINE');
INSERT INTO item_category (id, name) VALUES (2, 'APPAREL');
INSERT INTO item_category (id, name) VALUES (3, 'BEAUTY');
INSERT INTO item_category (id, name) VALUES (4, 'GROCERY');

INSERT INTO item (id, category_id, name, quantity, price) VALUES (1, 2, 'LP T-Shirt', 10, 2000);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (2, 2, 'LP Shirt', 50, 2500);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (3, 2, 'Wrogn T-Shirt', 200, 1000);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (4, 4, 'Instant Noodles (pack of 8)', 50, 200);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (5, 4, 'Lays Green', 100, 20);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (6, 4, 'Cadbury Dairy Milk (small)', 150, 40);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (7, 1, 'Cetzene', 500, 20);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (8, 1, 'Calpol', 250, 30);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (9, 1, 'Montek', 100, 80);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (10, 1, 'Digene', 500, 40);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (11, 3, 'Loreal Shampoo (large)', 50, 450);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (12, 3, 'Loreal Conditioner (large)', 50, 400);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (13, 3, 'Face Wash', 350, 300);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (14, 2, 'LP Suit', 5, 10000);
INSERT INTO item (id, category_id, name, quantity, price) VALUES (15, 4, 'Milk', 50, 30);